### ISSUE TITLE
Create Kubernetes artifacts for WSO2 Open Banking API Manager Deployment

### ISSUE THREAD

**Issue by KalanaDananjaya** [wso2/kubernetes-open-banking#2]
**Description:**
Create Kubernetes artifacts for deploying WSO2 Open Banking API Manager.

**Comment by chirangaalwis** [comment]
For this purpose, we can use either Kubernetes Deployments [1] or StatefulSets [2] depending on the context (e.g. the pattern and the WSO2 Open Banking product profiles used).

As of now, we have used purely Kubernetes Deployments for this purpose, in Helm resources for other WSO2 products.

Hence, it is required to evaluate how the appropriate contexts (e.g. deployments involving highly available API Manager Traffic Manager profile) need to be addressed using Kubernetes StatefulSets [3].

[1]: [Kubernetes Deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/)
[2]: [Kubernetes StatefulSet](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/)
[3]: [Move from Deployment resource to StatefulSet resource](https://github.com/wso2/kubernetes-apim/issues/72)

**Comment by KalanaDananjaya** [comment]
Introduced with https://github.com/wso2/kubernetes-open-banking/pull/13

For now we have use Kubernetes Deployments. We can improve these to use StatefulSets after further research
