### ISSUE TITLE
Rename the deployment pattern folders to match the chart name

### ISSUE THREAD

**Issue by KalanaDananjaya** [wso2/kubernetes-open-banking#35]
**Description:**
The prefix "simplified" is not added to the folder names eventhough it is present in the chart names. This needs to be fixed

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-open-banking/pull/36.

**Comment by chirangaalwis** [comment]
Addressed in https://github.com/wso2/kubernetes-open-banking/pull/38, again.
